sudo: false

language: php

php:
  - 5.6
  - 7
  - 7.1
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php:
        - nightly
        - hhvm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8d73a1cafd9bff5c96ee
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_script:
  - composer selfupdate
  - composer update

script:
  - mkdir -p build/logs
  # Run tests
  - php ./vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v
